### ISSUE TITLE
This fork is now referenced from ionic-native

### ISSUE THREAD

**Issue by oddcb** [mibrito707/cordova-plugin-secure-storage-echo#16]
Just a heads up that this fork now is the one referenced in ionic-native.

https://github.com/ionic-team/ionic-native/issues/3157

https://github.com/ionic-team/ionic-native/commit/a840a03e3338f3f0dca9b677065048829f78aaca

**Comment by mibrito707** [comment]
Awesome, thanks for let it me know @oddcb 😉

**Comment by timbru31** [comment]
I do not want to hijack/create a new issue, but nevertheless wanted to say: **thank you** for keeping this fork active and maintained!
