### ISSUE TITLE
Change Cipher on Android to support more than 128bit values

### ISSUE THREAD

**Issue by spike-rabbit** [mibrito707/cordova-plugin-secure-storage-echo#23]
The current Cipher mode `CCM` is not available on all Android APIs. At least some of them will fallback to ECB. This is a problem since ECB only supports values up to 128bits.
The official Documentation of Android Cipher does not list CCM as valid mode [(Android Doc)](https://developer.android.com/reference/javax/crypto/Cipher).
Therefore I would suggest changing the cipher mode to GCM.

In case somebody else is facing this issue, this is the error msg by Android was: `Uncaught Error: CCM packet too large for choice of q.`

After changing the Cipher mode the error was gone. When debugging AES.java with CIPHER_MODE="CCM" I noticed that AES-ECB was used. After switchting to GCM the desired Mode was used.

Can you please change the CIPHER_MODE to GCM or make it customizable so that it can be overriden by the app.

**Comment by markdon** [comment]
Sounds like this PR would solve your issue #17

**Comment by mibrito707** [comment]
Hey @spike-rabbit thanks for the report, can you use the latest version (5.0.1) to check if that resolve the issue.

**Comment by spike-rabbit** [comment]
5.0.1 is not published to npmjs.com, but I tried it with the current master and it worked.
