### ISSUE TITLE
android:sharedUserId is deprecated

### ISSUE THREAD

**Issue by szh** [mibrito707/cordova-plugin-secure-storage-echo#37]
From the Andoid docs:

> This constant was deprecated in API level 29.
Shared user IDs cause non-deterministic behavior within the package manager. As such, its use is strongly discouraged and may be removed in a future version of Android. Instead, apps should use proper communication mechanisms, such as services and content providers, to facilitate interoperability between shared components.

[https://developer.android.com/guide/topics/manifest/manifest-element#uid](https://developer.android.com/guide/topics/manifest/manifest-element#uid)

Is there an alternative way of providing shared data across applications that we can use?
Perhaps the README should be updated to warn that this feature might go away in a future Android release.

**Comment by mibrito707** [comment]
Hey @szh 
Thanks for let it me know, actually there are other ways of providing share data across applications, we can mention AIDL to implement a IPC, more info here: https://developer.android.com/guide/components/aidl
Right now there is no plan to implement it on this plugin but a PR is more than welcome.
Leaving this issue open for visibility.
