### ISSUE TITLE
Request for improved documentation 

### ISSUE THREAD

**Issue by aliantjamaica** [mibrito707/cordova-plugin-secure-storage-echo#39]
I am trying to refactor a my ionic 4 code to include cordova-plugin-secure-storage-echo instead of cordova-plugin-secure-storage. The problem is cordova-plugin-secure-storage is a dependency of @ionic-native/secure-storage and as such so would be cordova-plugin-secure-storage-echo but I see no documentation that speak to this. Also, when I try to use cordova to add cordova-plugin-secure-storage-echo I get the following error:

C:\coderepo\puppydogmobile\puppydogmobile>cordova plugin add cordova-plugin-secure-storage
Installing "cordova-plugin-secure-storage" for android
ANDROID_HOME=C:\Users\maenn\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_191
Subproject Path: CordovaLib

> Configure project :
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Could not find google-services.json while looking in [src/debug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/release]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :CordovaLib
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

> Task :clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clean'.
> Unable to delete file: C:\coderepo\puppydogmobile\puppydogmobile\platforms\android\build\intermediates\signing_config2\release\out\signing-config.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
1 actionable task: 1 executed
Failed to install 'cordova-plugin-secure-storage': Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\coderepo\puppydogmobile\puppydogmobile\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
cmd: Command failed with exit code 1

**Comment by aliantjamaica** [comment]
In addition to the above...If I use the latest (5.22.0)  @ionic-native/secure-storage then the use of 'SecureStorage' from @ionic-native/secure-storage result in a type error

**Comment by aliantjamaica** [comment]
>In addition to the above...If I use the latest (5.22.0) @ionic-native/secure-storage then the use of 'SecureStorage' from @ionic-native/secure-storage result in a type error 

I have discovered that the new format to import ionic plugins:
_**import { HTTP } from '@ionic-native/plugin-name/ngx';**_
for ionic 4+. This solved the Type error above

**Comment by aliantjamaica** [comment]
> I am trying to refactor a my ionic 4 code to include cordova-plugin-secure-storage-echo instead of cordova-plugin-secure-storage. The problem is cordova-plugin-secure-storage is a dependency of @ionic-native/secure-storage and as such so would be cordova-plugin-secure-storage-echo but I see no documentation that speak to this. Also, when I try to use cordova to add cordova-plugin-secure-storage-echo I get the following error:

Apparently you have to upgrade @ionic-native/secure-storage also but there is no mention of it in the doc. I updated it to 5.22.0 to get rid of the errors along with the required change to add _'ngx'_ to the import. The problem is because there is no documentation one can't be certain as to the consistency  and synchronization of the plugins. @mibrito707  can you look at this please.

**Comment by mibrito707** [comment]
Hey @aliantjamaica thanks for let it me know about this, this is actually a problem with the Ionic native documentation, not with this plugin.
There are opened issues in that repo, see: https://github.com/ionic-team/ionic-native/issues/3274 & https://github.com/ionic-team/ionic-native/issues/3230 can you please upvote and comment on those issues.
Also you can install  `@ionic-native/secure-storage-echo` instead, as you can see it's available in the latest ionic: https://github.com/ionic-team/ionic-native/tree/master/src/@ionic-native/plugins/secure-storage-echo

**Comment by aliantjamaica** [comment]
@mibrito707  Thanks for the update...
