### ISSUE TITLE
Update npm Package

### ISSUE THREAD

**Issue by Chuckv01** [mibrito707/cordova-plugin-secure-storage-echo#5]
Any way this fork could be published to the cordova-plugin-secure-storage npm package? If not might want to consider changing the name and publishing a new package.

**Comment by mibrito707** [comment]
I'm afraid there is no chance to re-publish to the previous npm package, but will focus on publish a new package very soon, thanks for the suggestion.

**Comment by s3rious** [comment]
It seems like @ggozad is kinda open to at least make a link to this fork at original repo: https://github.com/Crypho/cordova-plugin-secure-storage/issues/169#issuecomment-516726079

Maybe he'll pass you a right to a npm package? Did you've pm'd him?

But, btw, great work, you've saved my day.

**Comment by mibrito707** [comment]
Changed name and publishing as **cordova-plugin-secure-storage-echo**.
